// <auto-generated />
namespace InventoryManager2022.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IM22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IM22));
        
        string IMigrationMetadata.Id
        {
            get { return "202210131046486_IM22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
